### ISSUE TITLE
Add caching layer

### ISSUE THREAD

**Issue by wildlifehexagon** [dictyBase/graphql-server#4]
Can we put a Redis cache in front of GraphQL? Or should we put it on top of the protocol buffer?

Would need a unique string for GraphQL to be stored as a key, then this would need to be plugged into the server interceptor.

So maybe 15 lines of code -- 10 for the plugin (could use Badger, Redis, Bolt, CockroachDB), one line for gRPC layer, one for GraphQL layer.

Also: Redis would need to be added to each API server. Could use a command line flag `--no-cache` or something similar to make it easier to test.

**Comment by erichartline** [comment]
We could use [automatic persisted queries](https://gqlgen.com/reference/apq/). We would need to enable this on the [frontend](https://github.com/apollographql/apollo-link-persisted-queries) and then use Redis or something else on the server.

**Comment by erichartline** [comment]
note: cache will need to be cleaned on every mutation
